"""
Analytics generator - generates track.js helper file for tracking implementations.
"""

from typing import Dict, Any, List
from pathlib import Path
from ..tools.file_handler import FileHandler
from ..utils.formatters import format_markdown_code_block
from ..utils.logger import get_logger


class AnalyticsGenerator:
    """Generates track.js analytics helper code."""
    
    def __init__(self):
        """Initialize analytics generator."""
        self.logger = get_logger(__name__)
    
    def generate_track_js(self, suggestions: List[Dict[str, Any]]) -> str:
        """
        Generate track.js helper file from suggestions.
        
        Args:
            suggestions: List of tagging suggestions
        
        Returns:
            Generated track.js code
        """
        self.logger.info(f"Generating track.js for {len(suggestions)} events")
        
        # Generate track.js header
        code = """// Auto-generated Analytics Track Helper
// Generated by AIT System

export const trackEvent = (eventName, eventData = {}) => {
    // Track with Adobe Analytics
    if (window.adobeDataLayer) {
        window.adobeDataLayer.push({
            event: eventName,
            eventData: eventData
        });
    }
    
    // Fallback console logging
    console.log(`[Analytics] ${eventName}:`, eventData);
};

// Generated event tracking functions
"""
        
        # Generate individual tracking functions
        for suggestion in suggestions:
            event_name = suggestion.get("event_name", "event")
            action = suggestion.get("action", "unknown")
            
            code += f"""
export const track_{event_name.lower()} = (additionalData = {{}}) => {{
    trackEvent('{event_name}', {{
        action: '{action}',
        timestamp: new Date().toISOString(),
        ...additionalData
    }});
}};
"""
        
        self.logger.info("Generated track.js successfully")
        return code
    
    def save_track_js(self, code: str, output_path: Path) -> Path:
        """
        Save generated track.js file.
        
        Args:
            code: Generated code
            output_path: Where to save the file
        
        Returns:
            Path to saved file
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        FileHandler.write_file(output_path, code)
        self.logger.info(f"Saved track.js to {output_path}")
        return output_path
