const basicDlObject = {
  page: {
    name: '',
    channel: 'bpk',
    channelSession: '',
    displayChannel: 'Retail',
    sourceChannel: 'POS',
    flow: '',
    throttle: '',
  },
  user: {
    account: '',
    accountLast2: '',
    accountType: '',
    acctId_unhashed: '',
    authStatus: '',
    authType: '',
    customerRole: '',
    customerType: '',
    custId_unhashed: '',
    session: '',
    id: '',
    tenure: '',
    planType: '',
    zip: '',
  },
  target: { engagement: { intent: 'BILLPAYMENT EXPERIENCE' } },
  txn: {
    product: {},
    agent: '',
    agentRole: '',
    id: '',
    paymentType: '',
    paymentAmt: '',
    outletId: '',
    taxAmt: '',
    total: '',
    autoPay: '',
  },
  event: { value: '' },
  env: { businessUnit: '' },
  utils: {},
  search: {},
  support: {},
  cmp: {},
};

export default basicDlObject;
